<a href="https://colab.research.google.com/github/girijadesai390-web/Encoding-Practice/blob/main/Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [ ]:
data = {
    'Size': ['Medium', 'Small', 'Large', 'Medium', 'Small'],  # Ordinal feature
    'Color': ['Red', 'Blue', 'Green', 'Blue', 'Red']           # Nominal feature
}
df = pd.DataFrame(data)

In [ ]:
df

     Size  Color
0  Medium    Red
1   Small   Blue
2   Large  Green
3  Medium   Blue
4   Small    Red

In [ ]:
label_encoder = LabelEncoder()
df['Size_Encoded'] = label_encoder.fit_transform(df['Size'])

In [ ]:
df

     Size  Color  Size_Encoded
0  Medium    Red             1
1   Small   Blue             2
2   Large  Green             0
3  Medium   Blue             1
4   Small    Red             2

In [ ]:
df['Color_Encoded'] = label_encoder.fit_transform(df['Color'])

In [ ]:
one_hot_encoder = OneHotEncoder(sparse_output=False)
Size_encoded = one_hot_encoder.fit_transform(df[['Size']])

In [ ]:
df

     Size  Color  Size_Encoded  Color_Encoded
0  Medium    Red             1              2
1   Small   Blue             2              0
2   Large  Green             0              1
3  Medium   Blue             1              0
4   Small    Red             2              2

In [ ]:
Size_encoded

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
encoded_columns = one_hot_encoder.get_feature_names_out(['Size'])
ohe_df = pd.DataFrame(Size_encoded, columns=encoded_columns)

In [ ]:
ohe_df

   Size_Large  Size_Medium  Size_Small
0         0.0          1.0         0.0
1         0.0          0.0         1.0
2         1.0          0.0         0.0
3         0.0          1.0         0.0
4         0.0          0.0         1.0

In [ ]:
color_encoded = one_hot_encoder.fit_transform(df[['Color']])
encoded_columns = one_hot_encoder.get_feature_names_out(['Color'])
ohe_df2 = pd.DataFrame(color_encoded, columns=encoded_columns)
new_df= pd.concat([ohe_df,ohe_df2],axis=1)
new_df

   Size_Large  Size_Medium  Size_Small  Color_Blue  Color_Green  Color_Red
0         0.0          1.0         0.0         0.0          0.0        1.0
1         0.0          0.0         1.0         1.0          0.0        0.0
2         1.0          0.0         0.0         0.0          1.0        0.0
3         0.0          1.0         0.0         1.0          0.0        0.0
4         0.0          0.0         1.0         0.0          0.0        1.0

In [ ]:
final_df= pd.concat([df,new_df],axis=1)
final_df

,Size,Color,Size_Encoded,Color_Encoded,Size_Large,Size_Medium,Size_Small,Color_Blue,Color_Green,Color_Red
0,Medium,Red,1,2,0.0,1.0,0.0,0.0,0.0,1.0
1,Small,Blue,2,0,0.0,0.0,1.0,1.0,0.0,0.0
2,Large,Green,0,1,1.0,0.0,0.0,0.0,1.0,0.0
3,Medium,Blue,1,0,0.0,1.0,0.0,1.0,0.0,0.0
4,Small,Red,2,2,0.0,0.0,1.0,0.0,0.0,1.0